id: I97061AE1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T05:54:36+00:00'
last_modified: '2022-06-08T01:26:50.391272+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD44712
  title: སྟག་ལུང་ཐང་པ་བཀྲ་ཤིས་དཔལ་གྱི་རྣམ་ཐར་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    433C:
      image_group_id: I1PD44714
      title: ''
      total_pages: 232
      order: 1
      base_file: 433C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
