id: P004489
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:26:24.055920
source_metadata:
  id: bdr:W1PD44712
  title: སྟག་ལུང་ཐང་པ་བཀྲ་ཤིས་དཔལ་གྱི་རྣམ་ཐར་
  author: ''
  volumes:
    57fb1f6feb2b47da8f6dbedf43a6397b:
      image_group_id: I1PD44714
      title: ''
      volume_number: 1
      total_pages: 232
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
